### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by dometto** [libgit2/rugged#818] opened 2019-09-12 19:10 UTC
Sorry to bother everyone about this once again, but it would be great to know when you're planning to release a version of the gem that includes commits 3f614b1be7314f037f5d7d6b9a45a5b5e106862f  to db63415b3f01606e850dceea2554e8e8cf240265 from `master`. The next major release of [gollum](https://github.com/gollum/gollum) is hanging on this (we need the `rugged` update to be able to revert files). For `gollum` and other packages that depend on it, it's the last thing that's keeping us from ditching `grit`. And we would really, really like to ditch grit. :)

**Comment by bartkamphorst** [comment] 2019-09-19 11:49
@carlosmn @vmg Seconding this request for a new rugged release. Thanks in advance for making the time!

**Comment by dometto** [comment] 2019-10-13 11:49
Another reminder of this. Is anything holding up a minor version bump?

**Comment by bartkamphorst** [comment] 2019-10-27 14:01
Still looking for anyone willing and able to release another gem version of rugged. @arthurschreiber Could you help out?

**Comment by bartkamphorst** [comment] 2019-10-29 10:54
Or perhaps @stanhu could jump in for a new release?

**Comment by stanhu** [comment] 2019-10-30 13:59
I'm not actually involved with cutting new releases. @carlosmn Can you help here? Thanks!

**Comment by dometto** [comment] 2019-12-15 21:17
@tenderlove @carlosmn the two (or four, if you count the bumps) that were released four days ago still don't seem to contain the relevant changes. :-( Is there any reason for not including them?

**Comment by bartkamphorst** [comment] 2019-12-30 12:03
I can confirm that [Repository#diff_from_buffer(buffer)](https://github.com/libgit2/rugged/pull/790) and [Repository#apply(diff, options = {})](https://github.com/libgit2/rugged/pull/788) have not made it into the latest 0.28.4.1 release, despite having been merged into `master` in April. @carlosmn @vmg @tenderlove Could you please shine a light on why this is? Many thanks!

**Comment by mvz** [comment] 2020-01-05 16:45
It looks like 0.28.4.1 and 0.27.10.1 were released from the `maint/0.28` and `maint/0.27` branches, respectively. The `maint/0.28` branch was branched off master in February. This means that any pull requests merged into master after that time won't have been included.

**Comment by dometto** [comment] 2020-01-05 17:21
@mvz thanks for explaining!

@carlosmn @vmg: is there anything that speaks against doing a new release from master? Or should we open a PR with the relevant changes to the `maint/X` branches?

**Comment by dometto** [comment] 2020-03-06 12:35
libgit2 `v0.99` has been released. Is a corresponding rugged release planned? If so, could you please include the changes to rugged `master`? Many thanks!

**Closed** 2020-03-11 23:42 UTC
